
-- Vaciar todos los datos de pacientes y sus dependencias
-- usando TRUNCATE CASCADE para respetar FK automáticamente
TRUNCATE TABLE 
  patient_portal_audit,
  patient_portal_sessions,
  patient_portal_tokens,
  patient_auth_codes,
  contact_events,
  patient_deletion_audit,
  patient_transfers,
  patient_transfer_requests,
  collection_visits,
  collection_assignments,
  payment_audit_log,
  payment_reminder_log,
  credit_payments,
  payment_plan_installments,
  payment_plans,
  sale_payments,
  sale_items,
  promotor_comisiones,
  promotor_alerts,
  cash_movements,
  bank_transactions,
  expenses,
  lab_order_status_history,
  lab_orders,
  appointment_reminders,
  appointments,
  sales,
  clinical_ai_audit,
  clinical_marketing_actions,
  visual_exams,
  patient_prescriptions,
  campaign_exclusions,
  campaign_recipients,
  auto_message_logs,
  automated_message_log,
  cash_counts,
  cash_registers,
  patients
CASCADE;
